ruby:
  enabled: true
  config_file: .rubocop.yml

coffee_script:
  enabled: false

java_script:
  enabled: true
#  config_file: config/.jshint.json

scss:
  enabled: false
#  config_file: config/scss.yml
