# Database configuration
#
# If you wish to edit the username/password, change them in +.env+
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: gitflow_development

test:
  <<: *default
  database: gitflow_test

production:
  <<: *default
  database: gitflow_production
  username: <%= ENV['GITFLOW_DATABASE_USERNAME'] %>
  password: <%= ENV['GITFLOW_DATABASE_PASSWORD'] %>
